plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.netpickz'
version = '0.0.1-SNAPSHOT'
description = 'netpickz project for Spring Boot'

/*java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}*/

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web:3.5.3'
	implementation 'org.springframework.boot:spring-boot-devtools:3.5.0'
	
	//implementation 'org.springdoc:springdoc-openapi-starter-webmvc-api:2.8.8'
	// https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.5.4'
	// https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
	implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.3'
	// https://mvnrepository.com/artifact/org.projectlombok/lombok
	//implementation 'org.projectlombok:lombok:1.18.38'
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-webflux
	implementation 'org.springframework.boot:spring-boot-starter-webflux:3.5.0'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
	
}

tasks.named('test') {
	useJUnitPlatform()
}
