spring:
  application:
     name : Netpickz_back
  # database 연결
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO} 
#      ddl-auto: create 
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
     mail: 
      smtp:
       auth: true	
       starttls:
        enable: true    
  data:
    redis:
      host: ${REDIS_HOST}  # Redis 서버 주소
      port: ${REDIS_PORT}       # 기본 포트   
  jwt:
   secret: ${JWT_SECRET} # jwt 복호화 시 사용
server:
  servlet:
    context-path: /
    
logging:
  level:
    reactor.netty.http.client: DEBUG

#springdoc:
#  swagger-ui:
#    path :  /swagger-ui.html
  #api-docs:
   # path: /home

tmdb:
  api:
    key : ${TMDB_API_KEY}
  url : ${TMDB_URL}

app:
  front-url: ${FRONT_URL}