spring:
  application:
     name : Netpickz_back
  # database 연결
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/netpickz
    username: root
    password: 181128
    driver-class-name: org.mariadb.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
#      ddl-auto: create 
    
server:
  servlet:
    context-path: /
    
logging:
  level:
    reactor.netty.http.client: DEBUG

#springdoc:
#  swagger-ui:
#    path :  /swagger-ui.html
  #api-docs:
   # path: /home
   
#database
#spring.datasource.type
  