apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netpickz-test
  name: netpickz-back
  labels:
    part-of: k8s-netpickz
    component: backend-server
    name: netpickz-back
    instance: netpickz-back
    version: 1.0.1
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-netpickz
      component: backend-server
      name: netpickz_back
      instance: netpickz-back
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: k8s-netpickz
        component: backend-server
        name: netpickz_back
        instance: netpickz-back
        version: 1.0.1
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: netpickz-back
          image: yeji3479/netpickz_back:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: netpickz-back-sec
