apiVersion: v1
kind: Service
metadata:
  namespace: netpickz-test
  name: netpickz-test
  labels:
    part-of: k8s-netpickz
    component: backend-server
    name: netpickz_back
    instance: netpickz-test
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-netpickz
    component: backend-server
    name: netpickz_back
    instance: netpickz-test
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 32122
  type: NodePort
